# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-08 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desktop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('estado', models.CharField(choices=[('disponible', 'Item listo'), ('Vendido', 'Item Vendido'), ('Reponer', 'Reponer Item en la brevedad')], default='Vendido', max_length=10)),
                ('comentario', models.CharField(default='Sin Comentarios', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('estado', models.CharField(choices=[('disponible', 'Item listo'), ('Vendido', 'Item Vendido'), ('Reponer', 'Reponer Item en la brevedad')], default='Vendido', max_length=10)),
                ('comentario', models.CharField(default='Sin Comentarios', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('estado', models.CharField(choices=[('disponible', 'Item listo'), ('Vendido', 'Item Vendido'), ('Reponer', 'Reponer Item en la brevedad')], default='Vendido', max_length=10)),
                ('comentario', models.CharField(default='Sin Comentarios', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
